//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<short> TransactionTypeId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Comment { get; set; }

    }
}
